VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IDelayed"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit

Public Function Evaluate() As Variant
Attribute Evaluate.VB_UserMemId = 0

End Function
Public Function Map(ByVal op As IApplicable) As IDelayed

End Function
