VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IIterable"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit
'
' IIterable
' =========
'
' Has Indexed _read_ access
'
Public Function Item(ByVal index As Long) As Variant

End Function
Public Function LowerBound() As Long

End Function
Public Function UpperBound() As Long

End Function
