VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IOutput"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit

' print and end with new line
Public Sub PrintLine(Optional ByVal object As Variant)
End Sub

' print with no new line
' Name debatable.  `Print` is reserved :(
Public Sub Puts(Optional ByVal object As Variant)
End Sub


