VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IOutput"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit

' print with no new line
Public Sub Prints(ByVal x As Variant)

End Sub
' print and end with new line
Public Sub PrintLine(ByVal x As Variant)

End Sub
Public Sub PrintLines(ByRef xs() As Variant)

End Sub



