VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ISetLike"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit

Public Function Contains(ByVal sought) As Boolean
Attribute Contains.VB_UserMemId = 0

End Function
Public Property Get Elements() As IUnknown
Attribute Elements.VB_UserMemId = -4

End Property
Public Function Count() As Long

End Function
Public Function IsDisJoint(ByVal other As ISetLike) As Boolean

End Function
Public Function IsSubSetOf(ByVal other As ISetLike) As Boolean

End Function
Public Function IsProperSubSetOf(ByVal other As ISetLike) As Boolean

End Function
Public Function IsSuperSetOf(ByVal other As ISetLike) As Boolean

End Function
Public Function IsProperSuperSetOf(ByVal other As ISetLike) As Boolean

End Function
Public Function Union(ByVal other As ISetLike) As ISetLike
    
End Function
Public Function Intersect(ByVal other As ISetLike) As ISetLike

End Function
Public Function Difference(ByVal other As ISetLike) As ISetLike

End Function
Public Function SymmetricDifference(ByVal other As ISetLike) As ISetLike

End Function
