VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Linear"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit
'
' Linear
' =========
'
' Has Indexed _read_ access
'
Public Function Item(ByVal index As Long) As Variant
Attribute Item.VB_UserMemId = 0

End Function
Public Function LowerBound() As Long

End Function
Public Function UpperBound() As Long

End Function
'Public Function Size() As Long
'
'End Function
Public Function ToArray() As Variant()

End Function
Public Function ToCollection() As Collection

End Function
Public Function ToBuildable(ByVal seed As Buildable) As Buildable

End Function
'Public Function IndexWhere(ByVal pred As Applicable) As Maybe
'
'End Function
'Public Function IndexOf(ByVal val As Variant) As Maybe
'
'End Function
'Public Function LastIndexWhere(ByVal pred As Applicable) As Maybe
'
'End Function
'Public Function LastIndexOf(ByVal val As Variant) As Maybe
'
'End Function
'Public Function Find(ByVal pred As Applicable) As Maybe
'
'End Function
'Public Function FindLast(ByVal pred As Applicable) As Maybe
'
'End Function
'Public Function CountyWhere(ByVal pred As Applicable) As Long
'
'End Function
